{
  "_content": {
    "Summary": {
      "children": [
        {
          "type": "Paragraph",
          "data": {
            "inline": [
              {
                "type": "Words",
                "data": {
                  "value": "Ask the scheduler details of the sub-task of the given failed future"
                }
              }
            ],
            "inner": []
          }
        }
      ],
      "title": null
    },
    "Extended Summary": {
      "children": [
        {
          "type": "Paragraph",
          "data": {
            "inline": [
              {
                "type": "Words",
                "data": {
                  "value": "When a future evaluates to a status of \"error\", i.e., an exception was raised in a task within its graph, we an get information from the scheduler. This function gets the details of the specific task that raised the exception and led to the error, but does not fetch data from the cluster or execute the function."
                }
              }
            ],
            "inner": []
          }
        }
      ],
      "title": null
    },
    "Parameters": {
      "children": [
        {
          "type": "Param",
          "data": {
            "param": "future",
            "type_": "future that failed, having ``status==\"error\"``, typically",
            "desc": [
              {
                "type": "Paragraph",
                "data": {
                  "inline": [
                    {
                      "type": "Words",
                      "data": {
                        "value": "after an attempt to "
                      }
                    },
                    {
                      "type": "Verbatim",
                      "data": {
                        "value": [
                          "gather()"
                        ]
                      }
                    },
                    {
                      "type": "Words",
                      "data": {
                        "value": " shows a stack-stace."
                      }
                    }
                  ],
                  "inner": []
                }
              }
            ]
          }
        }
      ],
      "title": null
    },
    "Returns": {
      "children": [
        {
          "type": "Param",
          "data": {
            "param": "",
            "type_": "Tuple:",
            "desc": []
          }
        },
        {
          "type": "Param",
          "data": {
            "param": "",
            "type_": "- the function that raised an exception",
            "desc": []
          }
        },
        {
          "type": "Param",
          "data": {
            "param": "",
            "type_": "- argument list (a tuple), may include values and keys",
            "desc": []
          }
        },
        {
          "type": "Param",
          "data": {
            "param": "",
            "type_": "- keyword arguments (a dictionary), may include values and keys",
            "desc": []
          }
        },
        {
          "type": "Param",
          "data": {
            "param": "",
            "type_": "- list of keys that the function requires to be fetched to run",
            "desc": []
          }
        }
      ],
      "title": null
    },
    "Yields": {
      "children": [],
      "title": null
    },
    "Receives": {
      "children": [],
      "title": null
    },
    "Raises": {
      "children": [],
      "title": null
    },
    "Warns": {
      "children": [],
      "title": null
    },
    "Other Parameters": {
      "children": [],
      "title": null
    },
    "Attributes": {
      "children": [],
      "title": null
    },
    "Methods": {
      "children": [],
      "title": null
    },
    "Notes": {
      "children": [],
      "title": null
    },
    "Warnings": {
      "children": [],
      "title": null
    }
  },
  "refs": [],
  "ordered_sections": [
    "Summary",
    "Extended Summary",
    "Parameters",
    "Returns",
    "See Also"
  ],
  "item_file": "/Users/bussonniermatthias/dev/distributed/distributed/recreate_exceptions.py",
  "item_line": 92,
  "item_type": "<class 'function'>",
  "aliases": [
    "distributed.recreate_exceptions.ReplayExceptionClient.get_futures_error"
  ],
  "example_section_data": {
    "children": [],
    "title": null
  },
  "see_also": [
    {
      "name": {
        "name": "ReplayExceptionClient.recreate_error_locally",
        "ref": "distributed.recreate_exceptions.ReplayExceptionClient.recreate_error_locally",
        "exists": true
      },
      "descriptions": [],
      "type": null
    }
  ],
  "version": "2021.01.1+9.g613b3c820",
  "signature": "get_futures_error(self, future)",
  "references": null,
  "logo": "logo.png",
  "qa": "distributed.recreate_exceptions.ReplayExceptionClient.get_futures_error",
  "arbitrary": []
}